### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by Moo-cow** [pinple/douban-movie-extension#1]
右下角的开关无法打开

**Comment by pinple** [comment]
@Moo-cow 你好，感谢反馈，这个在Windows电脑的Chrome浏览器才有限制，由于我是在Mac电脑上开发的，所以没有发现这个问题

解决方法很简单，请参考：https://www.kancloud.cn/wangshubo1989/pit/100946

如还有问题，请继续反馈，谢谢~

**Comment by Moo-cow** [comment]
我用的7zip改后缀名后解压缩失败，我就压缩完再解压缩，报错：清单文件缺失或不可读取

**Comment by pinple** [comment]
@Moo-cow 是先鼠标右键改后缀为.zip，例如：douban-movie-v1.1.zip，然后把它解压到新的空的文件夹，然后再选择“加载已解压的扩展程序”，有小伙伴按照这个步骤在Windows电脑上成功安装了。如果还不行的话，试试换个解压工具呢？

**Comment by zd1980** [comment]
已经正常安装和使用啦

**Comment by Moo-cow** [comment]
蟹蟹！

**Comment by lsdhfsdhf** [comment]
感谢。 windows系统安装上之后，用一会之后还是会提示不在web store里，不可使用

**Comment by lsdhfsdhf** [comment]
> 感谢。 windows系统安装上之后，用一会之后还是会提示不在web store里，不可使用

又重新上载了一次，继续使用。

**Comment by pinple** [comment]
@lsdhfsdhf 好的。Windows也应该没问题的，之前已经有小伙伴用上了
