### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by KyleThanas** [pinple/douban-movie-extension#4]
该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。
https://support.google.com/chrome_webstore/answer/2811969?visit_id=636863280070937927-1301480990&p=ui_remove_non_cws_extensions&hl=zh-Hans&rd=2

**Comment by pinple** [comment]
@KyleThanas 
你好，由于该扩展没有在Chrome上架，所以被Chrome阻止了。但是还是可以使用的，请仔细阅读README.md中的“如何使用“和这个issue → #1
