### ISSUE TITLE
 该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。我的开发模式是打开的

### ISSUE THREAD

**Issue by cgq355716727** [pinple/douban-movie-extension#5]
该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。
我的开发模式是打开的
显示扩展被停用
windows 7 
Google Chrome
版本 71.0.3578.80

**Comment by pinple** [comment]
@cgq355716727 
先试试这两个办法：
- https://www.cnblogs.com/javalittleman/p/4070772.html  
- https://www.kancloud.cn/wangshubo1989/pit/100946

近两天遇到这个问题的越来越多，我在考虑上架到Chrome商店了。由于需要境外银行卡支付，比较麻烦，请给我点时间。

**Comment by pinple** [comment]
@cgq355716727  已在Chrome Web Store上架，猛戳：https://chrome.google.com/webstore/detail/%E8%B1%86%E7%93%A3%E7%94%B5%E5%BD%B1%E4%BC%A0%E9%80%81%E9%97%A8/pkidecliagangmpphpelecaoogfbnihi
