### ISSUE TITLE
需要支持吗?

### ISSUE THREAD

**Issue by mobailabs** [pinple/douban-movie-extension#6]
很棒,需要支持吗?我可以发布到谷歌商店.

**Comment by pinple** [comment]
@zhaopengme 太好了，方便的话帮我把最新版(v1.2)版本发布到Chrome商店吧，万分感谢。发布好了给我个链接吧，我更新一下README。

**Comment by mobailabs** [comment]
我弄好了,发你.

**Comment by mobailabs** [comment]
我去,刚刚发现,已经有人把你的上传了,是不是你本人啊!
https://chrome.google.com/webstore/detail/%E8%B1%86%E7%93%A3%E7%94%B5%E5%BD%B1%E4%BC%A0%E9%80%81%E9%97%A8/aljijcdnocnoaafhokpagbmidbfcdhko

**Comment by pinple** [comment]
@zhaopengme 咦，好像是我上传的，可是我还没有付钱啊，居然能搜到？你把你发布到链接给我吧。

**Comment by mobailabs** [comment]
https://chrome.google.com/webstore/detail/豆瓣电影传送门/pkidecliagangmpphpelecaoogfbnihi   这个

**Comment by pinple** [comment]
@zhaopengme 感谢大佬！
