### ISSUE TITLE
会被去广告插件拦截

### ISSUE THREAD

**Issue by loikein** [pinple/douban-movie-extension#7]
拦截列表：（然而单独关掉任何一个都没用）

- EasyList
- EasyPrivacy
- NoCoin
- EasyList China

**Comment by pinple** [comment]
@loikein 你好，我使用了ad block plus + 广告终结者，都使用了EasyList规则。并没有被拦截。见下图。
![Jietu20190319-223214.jpg](https://i.loli.net/2019/03/19/5c90fd9e787c0.jpg)
![Jietu20190319-223240.jpg](https://i.loli.net/2019/03/19/5c90fda054cfe.jpg)

**Comment by loikein** [comment]
您好，谢谢反馈！  
「在哪儿看这部电影」和「本片原声」都被拦截了，应该是`div class = gray_ad`的问题……？  
我用的是 Opera 自带的广告拦截功能。

**Comment by pinple** [comment]
> 您好，谢谢反馈！
> 「在哪儿看这部电影」和「本片原声」都被拦截了，应该是`div class = gray_ad`的问题……？
> 我用的是 Opera 自带的广告拦截功能。

「本片原声」都被拦截了，那就不是我这个插件的bug了，因为「本片原声」是豆瓣官方添加的，有可能是Opera浏览器自己的广告拦截策略有问题。我先close这个issue了，待确认是我插件的问题再打开。感谢支持。
